server:
  port: 8075


spring:
  profiles:
    active: dev1

  datasource:
    url: jdbc:mysql://localhost:3307/library2_db?serverTimezone=UTC
#    spring.datasource.url = jdbc:mysql://localhost:3307/library_db?serverTimezone=UTC
    username: root
    password: Gabriel1
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  security:
    user:
      name: Gabriel
      password: infomatic1
      user:
        roles: manager

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  # ==============================================================
  # = Spring Security / Queries for AuthenticationManagerBuilder
  # ==============================================================

  queries:
    users-query: select username, password, active from user where username=?
    roles-query: select username, role from user where username=?


  # ==============================================================
  # = Keep the connection alive if idle for a long time (needed in production)
  # ==============================================================
#  spring.datasource.testWhileIdle = true
#  spring.datasource.validationQuery = SELECT 1

  # ==============================================================
  # = Display log for each sql query (boolean)
  # ==============================================================
#  spring.jpa.show-sql = true



  # ==============================================================
  # = Spring Security / Queries for AuthenticationManagerBuilder
  # ==============================================================
#  spring.queries.users-query=select username, password, active from user where username=?
#  spring.queries.roles-query=select username, role from user where username=?

  # ==============================================================
  # = Initialize the database using data.sql script
  # ==============================================================
#  spring.datasource.initialization-mode=always